// <auto-generated />
using System;
using HotelBooking.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Api.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260805211112_SeedRooms")]
    partial class SeedRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Api.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBooking.Api.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Amenities = "WiFi,TV,Air Conditioning",
                            Description = "A comfortable standard room with a king bed, perfect for solo travelers or couples.",
                            ImageUrl = "https://picsum.photos/seed/room101/800/600",
                            IsActive = true,
                            MaxGuests = 2,
                            PricePerNight = 129.00m,
                            RoomNumber = "101",
                            RoomType = "Standard King"
                        },
                        new
                        {
                            RoomId = 2,
                            Amenities = "WiFi,TV,Air Conditioning",
                            Description = "A cozy standard room with a queen bed and modern amenities.",
                            ImageUrl = "https://picsum.photos/seed/room102/800/600",
                            IsActive = true,
                            MaxGuests = 2,
                            PricePerNight = 119.00m,
                            RoomNumber = "102",
                            RoomType = "Standard Queen"
                        },
                        new
                        {
                            RoomId = 3,
                            Amenities = "WiFi,TV,Air Conditioning,Mini Fridge",
                            Description = "A standard room with two double beds, ideal for small groups.",
                            ImageUrl = "https://picsum.photos/seed/room103/800/600",
                            IsActive = true,
                            MaxGuests = 3,
                            PricePerNight = 139.00m,
                            RoomNumber = "103",
                            RoomType = "Standard Double"
                        },
                        new
                        {
                            RoomId = 4,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,City View",
                            Description = "A spacious deluxe room with a king bed and city views.",
                            ImageUrl = "https://picsum.photos/seed/room201/800/600",
                            IsActive = true,
                            MaxGuests = 3,
                            PricePerNight = 189.00m,
                            RoomNumber = "201",
                            RoomType = "Deluxe King"
                        },
                        new
                        {
                            RoomId = 5,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,City View,Sofa Bed",
                            Description = "A deluxe suite with a separate seating area and a sofa bed.",
                            ImageUrl = "https://picsum.photos/seed/room202/800/600",
                            IsActive = true,
                            MaxGuests = 4,
                            PricePerNight = 219.00m,
                            RoomNumber = "202",
                            RoomType = "Deluxe Suite"
                        },
                        new
                        {
                            RoomId = 6,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning",
                            Description = "A deluxe room with two queen beds, great for families.",
                            ImageUrl = "https://picsum.photos/seed/room203/800/600",
                            IsActive = true,
                            MaxGuests = 4,
                            PricePerNight = 199.00m,
                            RoomNumber = "203",
                            RoomType = "Deluxe Double"
                        },
                        new
                        {
                            RoomId = 7,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,City View,Work Desk,Bathrobe",
                            Description = "An executive suite with a private work desk and premium comforts.",
                            ImageUrl = "https://picsum.photos/seed/room301/800/600",
                            IsActive = true,
                            MaxGuests = 4,
                            PricePerNight = 289.00m,
                            RoomNumber = "301",
                            RoomType = "Executive Suite"
                        },
                        new
                        {
                            RoomId = 8,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,Balcony",
                            Description = "A junior suite with a private balcony overlooking the city.",
                            ImageUrl = "https://picsum.photos/seed/room302/800/600",
                            IsActive = true,
                            MaxGuests = 3,
                            PricePerNight = 259.00m,
                            RoomNumber = "302",
                            RoomType = "Junior Suite"
                        },
                        new
                        {
                            RoomId = 9,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,City View,Jacuzzi,Private Balcony,Butler Service",
                            Description = "The ultimate luxury suite with a private jacuzzi and butler service.",
                            ImageUrl = "https://picsum.photos/seed/room401/800/600",
                            IsActive = true,
                            MaxGuests = 6,
                            PricePerNight = 599.00m,
                            RoomNumber = "401",
                            RoomType = "Presidential Suite"
                        },
                        new
                        {
                            RoomId = 10,
                            Amenities = "WiFi,TV,Minibar,Air Conditioning,Two Bedrooms,Kitchenette",
                            Description = "A spacious two-bedroom suite with a kitchenette, perfect for families.",
                            ImageUrl = "https://picsum.photos/seed/room402/800/600",
                            IsActive = true,
                            MaxGuests = 6,
                            PricePerNight = 349.00m,
                            RoomNumber = "402",
                            RoomType = "Family Suite"
                        });
                });

            modelBuilder.Entity("HotelBooking.Api.Models.Booking", b =>
                {
                    b.HasOne("HotelBooking.Api.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBooking.Api.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
